### PR TITLE
AUTH-482: set required-scc for openshift workloads

### PR DESCRIPTION
**Pull request by liouk**

### CODE REVIEW

**Comment by mpatlasov** [comment]
If I understand this PR correctly, it adds `openshift.io/required-scc: restricted-v2` only to `aws-ebs-csi-driver-controller` pods and deployment. Based on this [must-gather file](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_csi-operator/172/pull-ci-openshift-csi-operator-master-e2e-aws-ovn-upgrade/1760145300535644160/artifacts/e2e-aws-ovn-upgrade/gather-extra/artifacts/pods.json), all `aws-ebs-csi-driver-controller` pods run with annotation `"openshift.io/scc": "restricted-v2"`. Hence, adding `openshift.io/required-scc: restricted-v2` must be safe.

/lgtm
/approve

**Review by mpatlasov — APPROVED** [review]

**Comment by liouk** [comment]
> If I understand this PR correctly, it adds `openshift.io/required-scc: restricted-v2` only to `aws-ebs-csi-driver-controller` pods and deployment. Based on this [must-gather file](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_csi-operator/172/pull-ci-openshift-csi-operator-master-e2e-aws-ovn-upgrade/1760145300535644160/artifacts/e2e-aws-ovn-upgrade/gather-extra/artifacts/pods.json), all `aws-ebs-csi-driver-controller` pods run with annotation `"openshift.io/scc": "restricted-v2"`. Hence, adding `openshift.io/required-scc: restricted-v2` must be safe.

Thank you for verifying this @mpatlasov -- indeed I have chosen the SCC with which the pods are in fact getting admitted.

**Comment by liouk** [comment]
Hi @mpatlasov, I added some changes (basically added the annotation in `assets/base/node.yaml` and generated manifests properly), so `/lgtm` was dropped. Could you please take another look? Thanks!

**Comment by liouk** [comment]
No impact on docs or product experience.

/label docs-approved
/label px-approved

**Pull request merged**
