### PR TITLE
STOR-1856: remove aws efs operator legacy dir

### PR DESCRIPTION
**Pull request by RomanBednar**
Must merge after https://github.com/openshift/csi-operator/pull/237

cc @openshift/storage

### CODE REVIEW

**Comment by RomanBednar** [comment]
> DockerBuildFailed: Dockerfile build strategy has failed

This error is expected as the Dockerfiles need to be updated first not to use legacy dir in https://github.com/openshift/csi-operator/pull/237

**Comment by dobsonj** [comment]
/test all
We need to hold for https://github.com/openshift/release/pull/54571 and https://github.com/openshift-eng/ocp-build-data/pull/5120 to merge first though.

**Pull request merged**
