### PR TITLE
NO-JIRA: Add SidecarConfig.WithPatches

### PR DESCRIPTION
**Pull request by stephenfin**
To allow us to modify aspects of the default asset beyond 'args' without having to define a wholly new asset. We also add docs while we're here, mainly to emphasise that this shouldn't actually be used unless necessary.

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest-required
@stephenfin do you have an example of a CSI sidecar patch? Can you mention it in the commit message?

**Comment by stephenfin** [comment]
Yes, I'm using this in https://github.com/openshift/csi-operator/pull/275. You can see it used [here](https://github.com/openshift/csi-operator/pull/275/commits/c7c58c18207f0fc3ad143f53a2d35d5f57a3cc60#diff-9e4d5abc381c99fd5db77cd5b530830b31ceba8d952f57da3f095fa3bd7fcac8R62-R64).

**Comment by jsafrane** [comment]
/label px-approved
/label docs-approved
/label qe-approved
This is not an user-facing change + QE will be done as part of https://github.com/openshift/csi-operator/pull/275 (or the PR that switches Cinder operator image to the csi-operator based one.

**Pull request merged**
