### PR TITLE
OCPBUGS-42325: Set separate secrets for file and disk config on HyperShift

### PR DESCRIPTION
**Pull request by bryan-cox**
Set separate secrets for file and disk authentication config for Azure. Previously, these two components were reusing the same configuration as cloud provider.

### CODE REVIEW

**Comment by jsafrane** [comment]
It's a good idea to separate these secrets, is there a corresponding hypershift PR that _creates_ those secrets?

**Comment by bryan-cox** [comment]
> It's a good idea to separate these secrets, is there a corresponding hypershift PR that _creates_ those secrets?

Hey @jan--f - there isn't a PR at the moment but there will be in the near future. HyperShift would be responsible for creating/reconciling that within the HCP namespace.

**Comment by bryan-cox** [comment]
I opened https://github.com/openshift/hypershift/pull/4861 for now to correlate to this PR.

**Comment by Phaow** [comment]
Will do some intergration test with hypershift QE guys later when the configuration of cluster could be created.

**Pull request merged**
