### PR TITLE
OCPBUGS-26924: Add healthcheck for node-driver-registrar container

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://issues.redhat.com/browse/OCPBUGS-26924

### CODE REVIEW

**Comment by jsafrane** [comment]
Installation is stuck at:

> AzureDiskDriverNodeServiceControllerProgressing: Waiting for DaemonSet to deploy node pods

**Comment by gnufied** [comment]
```
    lastTransitionTime: '2024-02-01T22:11:59Z'
    message: '0/6 nodes are available: 1 node(s) didn''t have free ports for the requested
      pod ports. preemption: 0/6 nodes are available: 1 node(s) didn''t have free
      ports for the requested pod ports, 5 node(s) didn''t match Pod''s node affinity/selector.'
    reason: Unschedulable
```

**Comment by gnufied** [comment]
I have changed ports for EFS operator and now - in environments where we have 2 drivers (such ebs and efs), node-registrar-healthcheck will use `10304` and `10305`.

/hold cancel

**Pull request merged**
