### PR TITLE
[release-4.15] OCPBUGS-25355: setting TLSSecurityProfile with no minTLSVersion crashes controller

### PR DESCRIPTION
**Pull request by dobsonj**
bump library-go to get the fix in commit dc28c15393c9990e5ba0cd7612892bb88b6653cd

### CODE REVIEW

**Review by mpatlasov — APPROVED** [review]

**Comment by duanwei33** [comment]
Pre-merge test with open PR in AWS-EBS-CSI Driver, the result looks good:
0) Seting TLS profile in apiserver without version:
```
$ oc get apiserver cluster -o json | jq .spec.tlsSecurityProfile
{
  "custom": {
    "ciphers": [
      "ECDHE-ECDSA-CHACHA20-POLY1305",
      "ECDHE-ECDSA-AES128-GCM-SHA256"
    ]
  },
  "type": "Custom"
}
```
1) TLS profile in cm/config:
```
$ oc -n openshift-apiserver get cm config -o jsonpath="{.data.config\.yaml}" | jq .servingInfo
{
  "bindNetwork": "tcp",
  "cipherSuites": [
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
  ]
}
```

2) TLS profile in clustercsidriver
```
$ oc get clustercsidriver -o json ebs.csi.aws.com | jq .spec.observedConfig.targetcsiconfig.servingInfo
{
  "cipherSuites": [
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
  ],
  "minTLSVersion": ""
}
```

3) TLS profile in csi driver controller:
```
$ oc -n openshift-cluster-csi-drivers get deployment aws-ebs-csi-driver-controller -o json | jq .spec.template.spec.containers[] | jq 'select(.name | match(".*kube-rbac-proxy.*")) | {container: .name, arg: .args}'
{
  "container": "kube-rbac-proxy-8201",
  "arg": [
    "--secure-listen-address=0.0.0.0:9201",
    "--upstream=http://127.0.0.1:8201/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
{
  "container": "provisioner-kube-rbac-proxy",
  "arg": [
    "--secure-listen-address=0.0.0.0:9203",
    "--upstream=http://127.0.0.1:8203/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
{
  "container": "attacher-kube-rbac-proxy",
  "arg": [
    "--secure-listen-address=0.0.0.0:9204",
    "--upstream=http://127.0.0.1:8204/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
{
  "container": "resizer-kube-rbac-proxy",
  "arg": [
    "--secure-listen-address=0.0.0.0:9205",
    "--upstream=http://127.0.0.1:8205/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
{
  "container": "snapshotter-kube-rbac-proxy",
  "arg": [
    "--secure-listen-address=0.0.0.0:9206",
    "--upstream=http://127.0.0.1:8206/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
```

4) TLS profile is used in container:
```
The container kube-rbac-proxy-8201 in pod aws-ebs-csi-driver-controller-5698775f7c-4t25f:
1000220+       1       0  0 09:51 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9201 --upstream=http://127.0.0.1:8201/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
The container provisioner-kube-rbac-proxy in pod aws-ebs-csi-driver-controller-5698775f7c-4t25f:
1000220+       1       0  0 09:51 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9203 --upstream=http://127.0.0.1:8203/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
The container attacher-kube-rbac-proxy in pod aws-ebs-csi-driver-controller-5698775f7c-4t25f:
1000220+       1       0  0 09:51 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9204 --upstream=http://127.0.0.1:8204/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
The container resizer-kube-rbac-proxy in pod aws-ebs-csi-driver-controller-5698775f7c-4t25f:
1000220+       1       0  0 09:51 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9205 --upstream=http://127.0.0.1:8205/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
The container snapshotter-kube-rbac-proxy in pod aws-ebs-csi-driver-controller-5698775f7c-4t25f:
1000220+       1       0  0 09:51 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9206 --upstream=http://127.0.0.1:8206/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
```

**Pull request merged**
