### PR TITLE
OSASINFRA-3618: Add Cinder CSI support (part 3)

### PR DESCRIPTION
**Pull request by stephenfin**
This is part 3 of the process of merging the OpenStack Cinder CSI Driver operator into `csi-operator`.

This PR addresses the final step in the [migration guide][migration], namely removing code from `vendor/legacy` in this repository.

**Previous steps:**

- https://github.com/openshift/csi-operator/pull/278
- https://github.com/openshift/csi-operator/pull/281
- https://github.com/openshift/release/pull/56812
- https://github.com/openshift-eng/ocp-build-data/pull/5402
- https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/180
- https://github.com/openshift/csi-operator/pull/275
- https://github.com/openshift-eng/ocp-build-data/pull/5425
- https://github.com/openshift/release/pull/57034

[migration]: https://github.com/openshift/enhancements/blob/master/enhancements/storage/csi-driver-operator-merge.md#process-of-moving-operators-to-csi-operator-monorepo

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by stephenfin** [comment]
> Okay, no point retesting actually. Our CI job needs to be updated first. @MaysaMacedo has proposed this via [openshift/release#58561](https://github.com/openshift/release/pull/58561) and [openshift/csi-operator#316](https://github.com/openshift/csi-operator/pull/316).

There are merged now

**Comment by MaysaMacedo** [comment]
@gnufied 
This job shouldn't be running in this PR as it doesn't fulfill [the run_if_changed requirement](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml#L348) and it doesn't touch anything related to manila. I have reached out to the ocp-testplatform to understand why this is happening. While I don't hear back from them, can you consider overriding the manila-csi job?

**Pull request merged**
