### PR TITLE
OSASINFRA-3611: Add legacy csi-driver-manila-operator

### PR DESCRIPTION
**Pull request by MaysaMacedo**
- This PR moves the csi-driver-manila-operator into the legacy folder with the following command:
```
$ git remote add ocp git@github.com:openshift/csi-driver-manila-operator.git
$ git subtree add --prefix legacy/csi-driver-manila-operator ocp master --squash
```
- Adds the Dockerfile for building the operator image from new location

### CODE REVIEW

**Review by stephenfin — COMMENTED** [review]
- Merge is based on current `HEAD` of `master`, `f44d5ecddb5c6` :heavy_check_mark: 
- `Dockerfile.openstack-manila` looks sane :heavy_check_mark:

/lgtm
/approve

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by MaysaMacedo** [comment]
@gnufied could you also check the docs-approved and px-approved labels?

**Pull request merged**
