### PR TITLE
OCPBUGS-38815: add init container in EFS CSI controller pod

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/lgtm
/label backport-risk-assessed
Thanks for adding `terminationMessagePolicy: FallbackToLogsOnError` :)

**Comment by Phaow** [comment]
/label cherry-pick-approved
/label qe-approved

`aws-efs-operator-e2e-extended`  results looks good.

**Pull request merged**
