### PR TITLE
OSASINFRA-3609: Add Cinder CSI support (part 1)

### PR DESCRIPTION
**Pull request by stephenfin**
This is part 1 of the process of merging the OpenStack Cinder CSI Driver operator into `csi-operator`.

This PR follows the first three steps in the [migration guide][migration], namely:

1. Avoid `.gitignore` related footguns

   This was not an issue since our `.gitignore` only ignored the binary if it was in the root of the repo

2. Move existing code into `csi-operator` repository

3. Add Dockerfiles for building images from new location

https://github.com/openshift/release/pull/56812 will switch our jobs over to build images from this new location.

**Commits:**

- `Squashed 'legacy/openstack-cinder-csi-driver-operator/' content from commit dcac15afd`
- `openstack-cinder: Add Dockerfile`

[migration]: https://github.com/openshift/enhancements/blob/master/enhancements/storage/csi-driver-operator-merge.md#process-of-moving-operators-to-csi-operator-monorepo

### CODE REVIEW

**Comment by stephenfin** [comment]
/retitle OSASINFRA-3609: Add Cinder CSI support (step 1)

**Comment by stephenfin** [comment]
I think @openshift-ci is adding the `do-not-merge/invalid-owners-file` because an `OWNERS_ALIASES` cannot be placed outside of the top-level repo. Let's see.

**Comment by gnufied** [comment]
@stephenfin please ask storage QE to approve this PR in slack channel.

**Pull request merged**
