### PR TITLE
STOR-1713: Don't ignore azure-disk-csi-driver-operator

### PR DESCRIPTION
**Pull request by gnufied**
This should fix brewpub field.

### CODE REVIEW

**Comment by dobsonj** [comment]
/retitle STOR-1713: Don't ignore azure-disk-csi-driver-operator
/lgtm
/retest-required

**Comment by gnufied** [comment]
The build is btw failing because https://github.com/openshift/release/pull/47448/files#diff-d3c90828d0b4a3954ff9498d3c2196b600508244ece93a922fd3f8df79cc38fd PR/commit reverted my changes partly... I am trying to fix this.

**Comment by jsafrane** [comment]
CI has cached the src image somewhere, I created a new PR https://github.com/openshift/csi-operator/pull/111 with the same commit to see if it helps.

**Comment by jsafrane** [comment]
/override ci/prow/e2e-azure-csi
We need this merged to fix ART build. CI won't pass because they keep reverting our Dockerfile changes.

**Pull request merged**
