### PR TITLE
OSASINFRA-3609: Update legacy/openstack-cinder-csi-driver-operator

### PR DESCRIPTION
**Pull request by stephenfin**
Some new changes were merged into openstack-cinder-csi since https://github.com/openshift/csi-operator/pull/278 was proposed. Let's pull them in.

### CODE REVIEW

**Comment by stephenfin** [comment]
/retitle OSASINFRA-3609: Update legacy/openstack-cinder-csi-driver-operator

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
