### PR TITLE
OSASINFRA-3535: openstack-cinder: Watch management cluster for cloud-provider config

### PR DESCRIPTION
**Pull request by stephenfin**
We (unfortunately) need to extract our CA cert from the cloud-provider configuration. In a Hypershift context, this lives in the control plane cluster and has a different name. Correct both the cluster and name used and remove a check for missing config maps: this should *always* exist in a healthy cluster, given `cloud-provider-openstack` has a hard dependency on it.

### CODE REVIEW

**Comment by stephenfin** [comment]
I've tested this in a hypershift cluster and it works as expected. However, I'm maintaining the hold on this while we wait for the CI jobs to come back. iirc, there were some issues with `Clients.ControlPlaneKubeInformers` being `nil` in a standalone deployment. If that proves to be the case, we'll need to tweak this further. Or fix that issue (IMO, in a standalone deployment `ControlPlaneKubeInformers` should be identical to `KubeInformers`).

**Comment by EmilienM** [comment]
@stephenfin do we need an equivalent in Manila?

**Pull request merged**
