### PR TITLE
NO-JIRA: List all supported operators in README

### PR DESCRIPTION
**Pull request by stephenfin**
Update the README to list all currently supported operators.

### CODE REVIEW

**Comment by jsafrane** [comment]
/label px-approved
/label docs-approved
/label qe-approved
This updates only README
/retest-required

**Comment by stephenfin** [comment]
/relabel NO-JIRA: List all supported operators in README

**Comment by stephenfin** [comment]
/retitle NO-JIRA: List all supported operators in README

**Comment by jsafrane** [comment]
/override ci/prow/hypershift-aws-e2e-external
cough cough

**Pull request merged**
