### PR TITLE
STOR-1402, STOR-1453: update libraries and specify TLS_MIN_VERSION

### PR DESCRIPTION
**Pull request by dobsonj**
- [STOR-1402](https://issues.redhat.com//browse/STOR-1402): Chore: update libraries in all operators [4.15]
- [STOR-1453](https://issues.redhat.com//browse/STOR-1453): Specify TLS_MIN_VERSION in kube-rbac-proxy

/hold
for QE testing

/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
It's using the wrong dockerfile again (-_-)
```
            "name": "manage-dockerfile",
            "state": {
              "terminated": {
                "exitCode": 1,
                "reason": "Error",
                "message": "error: open /tmp/build/inputs/Dockerfile.rhel7: no such file or directory\n",
                "startedAt": "2023-11-20T19:56:44Z",
                "finishedAt": "2023-11-20T19:56:44Z",
                "containerID": "cri-o://21ed6aabfdada3823c3748143abcfe8dd8857f7fe0b4d810cc2db3997acc31ca"
              }
```
Fix: https://github.com/openshift/release/pull/45886

**Comment by duanwei33** [comment]
Test with open PR https://github.com/openshift/csi-operator/pull/69 and https://github.com/openshift/csi-operator/pull/71:
1) TLS profile in cm/config:
$ oc -n openshift-apiserver get cm config -o jsonpath="{.data.config\.yaml}" | jq .servingInfo
```
{
  "bindNetwork": "tcp",
  "cipherSuites": [
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
  ],
  "minTLSVersion": "VersionTLS12"
}
```

2) TLS profile in clustercsidriver
```
$ oc get clustercsidriver -o json ebs.csi.aws.com | jq .spec.observedConfig.targetcsiconfig.servingInfo
{
  "cipherSuites": [
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
  ],
  "minTLSVersion": "VersionTLS12"
}
```

3) TLS profile in csi driver controller:
```
$ oc -n openshift-cluster-csi-drivers get deployment aws-ebs-csi-driver-controller -o json | jq .spec.template.spec.containers[] | jq 'select(.name | match(".*kube-rbac-proxy.*")) | {container: .name, arg: .args}'
{
  "container": "kube-rbac-proxy-8201",
  "arg": [
    "--secure-listen-address=0.0.0.0:9201",
    "--upstream=http://127.0.0.1:8201/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
{
  "container": "provisioner-kube-rbac-proxy",
  "arg": [
    "--secure-listen-address=0.0.0.0:9203",
    "--upstream=http://127.0.0.1:8203/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
{
  "container": "attacher-kube-rbac-proxy",
  "arg": [
    "--secure-listen-address=0.0.0.0:9204",
    "--upstream=http://127.0.0.1:8204/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
{
  "container": "resizer-kube-rbac-proxy",
  "arg": [
    "--secure-listen-address=0.0.0.0:9205",
    "--upstream=http://127.0.0.1:8205/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
{
  "container": "snapshotter-kube-rbac-proxy",
  "arg": [
    "--secure-listen-address=0.0.0.0:9206",
    "--upstream=http://127.0.0.1:8206/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
```

4) TLS profile is used in container:
```
The container kube-rbac-proxy-8201 in pod aws-ebs-csi-driver-controller-7d86b8bf97-7qqwx:
1000270+       1       0  0 00:58 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9201 --upstream=http://127.0.0.1:8201/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
The container provisioner-kube-rbac-proxy in pod aws-ebs-csi-driver-controller-7d86b8bf97-7qqwx:
1000270+       1       0  0 00:58 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9203 --upstream=http://127.0.0.1:8203/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
The container attacher-kube-rbac-proxy in pod aws-ebs-csi-driver-controller-7d86b8bf97-7qqwx:
1000270+       1       0  0 00:58 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9204 --upstream=http://127.0.0.1:8204/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
The container resizer-kube-rbac-proxy in pod aws-ebs-csi-driver-controller-7d86b8bf97-7qqwx:
1000270+       1       0  0 00:58 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9205 --upstream=http://127.0.0.1:8205/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
The container snapshotter-kube-rbac-proxy in pod aws-ebs-csi-driver-controller-7d86b8bf97-7qqwx:
1000270+       1       0  0 00:58 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9206 --upstream=http://127.0.0.1:8206/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
-------------------------------------------
```

**Comment by duanwei33** [comment]
Also tested on hosted cluster:
1. The original TLS profile parameters is set well in Drivers/controller
2. When updating the TLS profile parameters in HostedControlPlane spec.configuration.apiServer, the parameters don't get updated accordingly. Jira [OCPBUGS-23922](https://issues.redhat.com/browse/OCPBUGS-23922) and [STOR-1612](https://issues.redhat.com/browse/STOR-1612) are tracked.
 
From QE's side, although it might doesn't work well on hypershift when the TLS profile is updated, I could be tracked by Jiras and fixed later.

**Pull request merged**
